import { z } from 'zod';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { resumeSchema,configSchema,plans,canTransition,paymentMatches,verifyHmac } from '@/lib/contracts';
import { db,runtime,user,config,configured,paymentReady,ownedOrder,limited,bounded,jsonBody,sameOrigin,razor,reply,HttpError,now } from '@/lib/service';
export const dynamic='force-dynamic';
const idSchema=z.string().uuid();
async function markCaptured(o:any,p:any){if(!paymentMatches(p,o))throw new HttpError(409,'Payment is not captured for this order and amount.');await db().prepare("UPDATE orders SET payment_status='captured',payment_id=?,status=CASE WHEN status='awaiting_payment' THEN 'paid' ELSE status END,updated_at=? WHERE id=? AND payment_status='pending'").bind(p.id,now(),o.id).run();}
async function handle(req:Request){
 const url=new URL(req.url),parts=url.pathname.replace(/^\/api\//,'').split('/'),route=parts[0],id=parts[1],action=parts[2],method=req.method;
 if(route==='webhook'&&method==='POST'){
  const secret=runtime().RAZORPAY_WEBHOOK_SECRET;if(!secret)throw new HttpError(503,'Webhook is not configured.');
  const raw=new TextDecoder().decode(await bounded(req));if(!await verifyHmac(secret,raw,req.headers.get('x-razorpay-signature')||''))throw new HttpError(400,'Invalid signature.');
  const event=JSON.parse(raw);const p=event.payload?.payment?.entity;
  if(event.event==='payment.captured'&&p?.order_id){const o=await db().prepare('SELECT * FROM orders WHERE provider_order_id=?').bind(p.order_id).first<any>();if(o)await markCaptured(o,p);}
  if(event.event==='refund.processed'){const r=event.payload?.refund?.entity;if(r?.payment_id){const o=await db().prepare('SELECT * FROM orders WHERE payment_id=?').bind(r.payment_id).first<any>();if(o){const p=await razor('payments/'+encodeURIComponent(o.payment_id));if(p.amount_refunded===o.amount)await db().prepare("UPDATE orders SET status='refunded',payment_status='refunded',updated_at=? WHERE id=?").bind(now(),o.id).run();}}}
  return reply({ok:true});
 }
 if(method!=='GET')sameOrigin(req);
 if(route==='config'&&method==='GET'){const c=await config();return reply({config:c,ready:configured(c)&&paymentReady()&&c.acceptingOrders});}
 if(route==='me'&&method==='GET'){const u=await getChatGPTUser();return reply({user:u?{email:u.email,name:u.displayName,admin:!!runtime().ADMIN_EMAIL&&u.email.toLowerCase()===runtime().ADMIN_EMAIL!.toLowerCase()}:null});}
 const u=await user();
 if(method!=='GET')await limited(u.userId+':writes',150);
 if(route==='admin'){
  if(!u.admin)throw new HttpError(403,'Owner access required.');
  if(method==='GET')return reply({config:await config(),paymentConfigured:paymentReady(),orders:(await db().prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 500').all()).results});
  if(method==='POST'&&id==='settings'){const c=configSchema.parse(await jsonBody(req));if(c.acceptingOrders&&(!configured(c)||!paymentReady()))throw new HttpError(400,'Complete business details, policies and live payment secrets before opening orders.');await db().prepare('INSERT INTO settings (id,data) VALUES (?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind('launch',JSON.stringify(c)).run();return reply({ok:true});}
 }
 if(route==='resumes'){
  if(method==='GET'&&!id)return reply({resumes:(await db().prepare('SELECT id,title,updated_at FROM resumes WHERE user_id=? ORDER BY updated_at DESC LIMIT 100').bind(u.userId).all()).results});
  if(id)idSchema.parse(id);
  if(method==='GET'&&id){const row=await db().prepare('SELECT * FROM resumes WHERE id=? AND user_id=?').bind(id,u.userId).first<any>();if(!row)throw new HttpError(404,'Resume not found.');return reply({...row,data:JSON.parse(row.data)});}
  if(method==='DELETE'&&id){await db().prepare('DELETE FROM resumes WHERE id=? AND user_id=?').bind(id,u.userId).run();return reply({ok:true});}
  if(method==='POST'){const b=z.object({title:z.string().trim().min(1).max(100),data:resumeSchema}).parse(await jsonBody(req));const rid=id||crypto.randomUUID();
   if(id){const r=await db().prepare('UPDATE resumes SET title=?,data=?,updated_at=? WHERE id=? AND user_id=?').bind(b.title,JSON.stringify(b.data),now(),id,u.userId).run();if(!r.meta.changes)throw new HttpError(404,'Resume not found.');}
   else {const result=await db().prepare('INSERT INTO resumes (id,user_id,title,data,updated_at) SELECT ?,?,?,?,? WHERE (SELECT COUNT(*) FROM resumes WHERE user_id=?)<100').bind(rid,u.userId,b.title,JSON.stringify(b.data),now(),u.userId).run();if(!result.meta.changes)throw new HttpError(409,'You can save up to 100 resumes. Delete one to add another.');}
   return reply({id:rid});}
 }
 if(route==='orders'){
  if(method==='GET'&&!id)return reply({orders:(await db().prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(u.userId).all()).results});
  if(method==='POST'&&!id){const b=z.object({plan:z.enum(['review','rewrite']),brief:z.string().trim().min(20).max(10000),accept:z.literal(true)}).parse(await jsonBody(req));const c=await config();if(!c.acceptingOrders||!configured(c)||!paymentReady())throw new HttpError(503,'Paid services are not accepting orders yet. The free builder is available.');await limited(u.userId+':orders',10);const oid=crypto.randomUUID(),amount=(b.plan==='review'?c.reviewPrice:c.rewritePrice)*100;const time=now();
   await db().prepare('INSERT INTO orders (id,user_id,email,plan,amount,status,payment_status,brief,snapshot,revisions,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,0,?,?)').bind(oid,u.userId,u.email,b.plan,amount,'awaiting_payment','pending',b.brief,JSON.stringify({name:plans[b.plan].name,deliveryDays:c.deliveryDays,terms:c.terms,refundPolicy:c.refundPolicy,privacy:c.privacy,businessName:c.businessName,businessAddress:c.businessAddress,supportEmail:c.supportEmail,acceptedAt:time}),time,time).run();return reply({id:oid},201);}
  idSchema.parse(id);const o=await ownedOrder(id,u);
  if(method==='GET')return reply({order:o,messages:(await db().prepare('SELECT * FROM messages WHERE order_id=? ORDER BY created_at ASC LIMIT 500').bind(id).all()).results,files:(await db().prepare('SELECT id,name,kind,created_at FROM files WHERE order_id=? ORDER BY created_at ASC').bind(id).all()).results});
  if(method==='POST'&&action==='message'){const b=z.object({body:z.string().trim().min(1).max(4000)}).parse(await jsonBody(req));await db().prepare('INSERT INTO messages (id,order_id,author,body,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,u.admin?'FirstCV':'Customer',b.body,now()).run();return reply({ok:true});}
  if(method==='POST'&&action==='cancel'){const r=await db().prepare("UPDATE orders SET status='cancelled',updated_at=? WHERE id=? AND payment_status='pending' AND provider_order_id IS NULL AND status='awaiting_payment'").bind(now(),id).run();if(!r.meta.changes)throw new HttpError(409,'A payment may already be underway. Contact support using this order.');return reply({ok:true});}
  if(method==='POST'&&action==='revision'){const r=await db().prepare("UPDATE orders SET status='revision_requested',revisions=revisions+1,updated_at=? WHERE id=? AND status='delivered' AND revisions<1 AND payment_status='captured'").bind(now(),id).run();if(!r.meta.changes)throw new HttpError(409,'One revision is available after delivery.');return reply({ok:true});}
  if(method==='POST'&&action==='refund-request'){const b=z.object({reason:z.string().trim().min(10).max(2000)}).parse(await jsonBody(req));if(o.payment_status!=='captured')throw new HttpError(409,'Only captured payments can be refunded.');await db().batch([db().prepare("UPDATE orders SET status='refund_requested',updated_at=? WHERE id=? AND payment_status='captured'").bind(now(),id),db().prepare('INSERT INTO messages (id,order_id,author,body,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,u.admin?'FirstCV':'Customer','Refund requested: '+b.reason,now())]);return reply({ok:true});}
  if(method==='POST'&&action==='status'){if(!u.admin)throw new HttpError(403,'Owner access required.');const b=z.object({status:z.enum(['in_progress','delivered','completed'])}).parse(await jsonBody(req));if(o.payment_status!=='captured'||!canTransition(o.status,b.status))throw new HttpError(409,'This order cannot move to that status.');if(b.status==='delivered'&&!await db().prepare("SELECT id FROM files WHERE order_id=? AND kind='delivery'").bind(id).first())throw new HttpError(409,'Upload a delivery PDF first.');const r=await db().prepare('UPDATE orders SET status=?,updated_at=? WHERE id=? AND status=?').bind(b.status,now(),id,o.status).run();if(!r.meta.changes)throw new HttpError(409,'Order changed. Refresh and try again.');return reply({ok:true});}
  if(method==='POST'&&action==='checkout'){
   if(o.payment_status!=='pending'||o.status!=='awaiting_payment')throw new HttpError(409,'This order does not need payment.');if(!paymentReady())throw new HttpError(503,'Payments are currently unavailable.');await limited(u.userId+':checkout',20);
   let remote=o.provider_order_id;
   if(remote?.startsWith('creating:'))throw new HttpError(409,'Payment setup is still being confirmed. Refresh shortly or contact support.');
   if(!remote){const lock=await db().prepare("UPDATE orders SET provider_order_id=? WHERE id=? AND provider_order_id IS NULL").bind('creating:'+id,id).run();if(!lock.meta.changes)throw new HttpError(409,'Checkout is being prepared. Refresh this order.');
    const made=await razor('orders',{amount:o.amount,currency:'INR',receipt:id,notes:{firstcv_order_id:id}});
    if(!/^order_[a-zA-Z0-9]+$/.test(made.id)||made.amount!==o.amount||made.currency!=='INR')throw new HttpError(502,'Payment setup needs support review.');remote=made.id;await db().prepare('UPDATE orders SET provider_order_id=?,updated_at=? WHERE id=?').bind(remote,now(),id).run();}
   return reply({key:runtime().RAZORPAY_KEY_ID,order_id:remote,amount:o.amount,currency:'INR',name:'FirstCV',prefill:{email:o.email}});
  }
  if(method==='POST'&&action==='recover-checkout'){if(!u.admin)throw new HttpError(403,'Owner access required.');const b=z.object({providerOrderId:z.string().regex(/^order_[a-zA-Z0-9]+$/)}).parse(await jsonBody(req));if(!o.provider_order_id?.startsWith('creating:'))throw new HttpError(409,'This checkout does not need recovery.');const remote=await razor('orders/'+b.providerOrderId);if(remote.receipt!==id||remote.amount!==o.amount||remote.currency!=='INR')throw new HttpError(409,'Provider order does not match this FirstCV order.');await db().prepare('UPDATE orders SET provider_order_id=?,updated_at=? WHERE id=? AND provider_order_id=?').bind(remote.id,now(),id,o.provider_order_id).run();return reply({ok:true});}
  if(method==='POST'&&action==='verify'){const b=z.object({razorpay_payment_id:z.string().regex(/^pay_[a-zA-Z0-9]+$/),razorpay_order_id:z.string(),razorpay_signature:z.string()}).parse(await jsonBody(req));if(b.razorpay_order_id!==o.provider_order_id||!await verifyHmac(runtime().RAZORPAY_KEY_SECRET||'',o.provider_order_id+'|'+b.razorpay_payment_id,b.razorpay_signature))throw new HttpError(400,'Payment verification failed.');await markCaptured(o,await razor('payments/'+b.razorpay_payment_id));return reply({ok:true});}
  if(method==='POST'&&action==='reconcile'){await limited(u.userId+':reconcile',30);if(!o.provider_order_id||o.provider_order_id?.startsWith('creating:'))throw new HttpError(409,'Payment setup has not completed. Contact support.');const result=await razor('orders/'+encodeURIComponent(o.provider_order_id)+'/payments');const payment=result.items?.find((p:any)=>paymentMatches(p,o));if(payment)await markCaptured(o,payment);if(o.payment_id){const p=await razor('payments/'+encodeURIComponent(o.payment_id));if(p.amount_refunded===o.amount&&p.currency==='INR')await db().prepare("UPDATE orders SET status='refunded',payment_status='refunded',updated_at=? WHERE id=?").bind(now(),id).run();}return reply({ok:true});}
  if(method==='POST'&&action==='file'){const bytes=await bounded(req,5*1024*1024);if(new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')throw new HttpError(400,'Upload a PDF file, up to 5 MB.');const count=await db().prepare('SELECT COUNT(*) AS total FROM files WHERE order_id=?').bind(id).first<{total:number}>();if((count?.total||0)>=20)throw new HttpError(409,'This order has reached its 20-file limit.');const fid=crypto.randomUUID(),key='orders/'+id+'/'+fid;let name=decodeURIComponent(req.headers.get('x-file-name')||'document.pdf').replace(/[^a-zA-Z0-9_. -]/g,'_').slice(0,100);if(!name.endsWith('.pdf'))name+='.pdf';await runtime().BUCKET.put(key,bytes,{httpMetadata:{contentType:'application/pdf'}});try{await db().prepare('INSERT INTO files (id,order_id,name,object_key,kind,created_at) VALUES (?,?,?,?,?,?)').bind(fid,id,name,key,u.admin?'delivery':'source',now()).run();}catch(e){await runtime().BUCKET.delete(key);throw e;}return reply({ok:true});}
 }
 if(route==='files'&&method==='GET'){idSchema.parse(id);const f=await db().prepare('SELECT * FROM files WHERE id=?').bind(id).first<any>();if(!f)throw new HttpError(404,'File not found.');await ownedOrder(f.order_id,u);const file=await runtime().BUCKET.get(f.object_key);if(!file)throw new HttpError(404,'File not found.');return new Response(file.body,{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${f.name}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}
 throw new HttpError(404,'Not found.');
}
async function endpoint(req:Request){try{return await handle(req);}catch(e){if(e instanceof HttpError)return reply({error:e.message},e.status);if(e instanceof z.ZodError)return reply({error:'Please check the required fields and their length.'},400);console.error('FirstCV request failed',e instanceof Error?e.name:'unknown');return reply({error:'This request could not be completed. Your input has not been cleared. Please try again.'},503);}}
export const GET=endpoint;export const POST=endpoint;export const DELETE=endpoint;
