import { z } from 'zod';
const short=z.string().max(8000);
export const resumeSchema=z.object({version:z.literal(1),template:z.enum(['modern','classic','compact']),accent:z.string().regex(/^#[0-9a-f]{6}$/i),sample:z.boolean().default(false),profile:z.object({name:short,role:short,email:short,phone:short,location:short,website:short,summary:short}),education:z.array(z.object({degree:short,school:short,period:short,details:short})).max(30),experience:z.array(z.object({title:short,company:short,period:short,details:short})).max(30),projects:z.array(z.object({name:short,stack:short,link:short,details:short})).max(30),skills:short,languages:short,job:z.string().max(30000).default('')});
export const configSchema=z.object({businessName:z.string().trim().max(120),supportEmail:z.union([z.string().email(),z.literal('')]),businessAddress:z.string().trim().max(1000),reviewPrice:z.number().int().min(100).max(100000),rewritePrice:z.number().int().min(100).max(100000),deliveryDays:z.number().int().min(1).max(30),refundPolicy:z.string().max(5000),terms:z.string().max(8000),privacy:z.string().max(8000),acceptingOrders:z.boolean()});
export const defaults={businessName:'',supportEmail:'',businessAddress:'',reviewPrice:299,rewritePrice:599,deliveryDays:3,refundPolicy:'Request cancellation before work begins for a full refund. If work has started, contact support to discuss the work already completed. Refunds approved by the operator are returned through the original payment method; bank processing time varies.',terms:'FirstCV provides resume formatting and writing assistance based on information you supply. We do not invent qualifications, employment history, or results, and do not guarantee interviews, employment, or ATS ranking. Each paid service includes one revision. Delivery starts after payment and receipt of complete requirements.',privacy:'The free editor keeps a draft in your browser. When signed in, you can choose to save resumes to your account. Service orders, messages, uploaded PDFs, and payment references are stored to deliver your order. Payment card details are handled by Razorpay, not FirstCV. Resume data is not sent to an AI service. You can delete saved resumes from your account. Contact support for order-data access or deletion requests; transaction records may need to be retained for required business records.',acceptingOrders:false};
export const plans={review:{name:'Resume Review',description:'A written review of clarity, structure, and relevance, with actionable feedback.',features:['Detailed PDF review','Job-description alignment feedback','One follow-up revision']},rewrite:{name:'Resume Makeover',description:'Resume rewriting and formatting using your real experience, projects, and strengths.',features:['Rewritten, formatted resume PDF','One target role','One revision after delivery']}};
export function canTransition(from:string,to:string){return ({paid:['in_progress'],in_progress:['delivered'],revision_requested:['in_progress'],delivered:['completed']} as Record<string,string[]>)[from]?.includes(to)??false;}
export function paymentMatches(payment:any,order:any){return payment?.order_id===order.provider_order_id&&payment?.amount===order.amount&&payment?.currency==='INR'&&payment?.status==='captured';}
export async function verifyHmac(secret:string,payload:string,signature:string){if(!/^[0-9a-f]{64}$/i.test(signature))return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const bytes=Uint8Array.from(signature.match(/../g)!,x=>parseInt(x,16));return crypto.subtle.verify('HMAC',key,bytes,new TextEncoder().encode(payload));}
