import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { defaults,configSchema } from './contracts';
export const runtime=()=>env as unknown as {DB:D1Database;BUCKET:R2Bucket;ADMIN_EMAIL?:string;RAZORPAY_KEY_ID?:string;RAZORPAY_KEY_SECRET?:string;RAZORPAY_WEBHOOK_SECRET?:string};
export function db(){const d=runtime().DB;if(!d)throw new HttpError(503,'Storage is temporarily unavailable. Please try again.');return d;}
export class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
export const now=()=>new Date().toISOString();
export async function user(){const u=await getChatGPTUser();if(!u)throw new HttpError(401,'Sign in with ChatGPT to continue.');return {...u,admin:!!runtime().ADMIN_EMAIL&&u.email.toLowerCase()===runtime().ADMIN_EMAIL!.toLowerCase()};}
export async function config(){const row=await db().prepare('SELECT data FROM settings WHERE id=?').bind('launch').first<{data:string}>();return row?configSchema.parse(JSON.parse(row.data)):defaults;}
export function configured(c:typeof defaults){return !!(c.businessName&&c.supportEmail&&c.businessAddress&&c.terms.length>=30&&c.privacy.length>=30&&c.refundPolicy.length>=30);}
export function paymentReady(){const e=runtime();return !!(e.RAZORPAY_KEY_ID?.startsWith('rzp_live_')&&e.RAZORPAY_KEY_SECRET&&e.RAZORPAY_WEBHOOK_SECRET);}
export async function ownedOrder(id:string,u:Awaited<ReturnType<typeof user>>){const row=await db().prepare('SELECT * FROM orders WHERE id=?').bind(id).first<any>();if(!row||(!u.admin&&row.user_id!==u.userId))throw new HttpError(404,'Order not found.');return row;}
export async function limited(id:string,max=60){const time=Math.floor(Date.now()/1000);const record=await db().prepare('INSERT INTO limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN expires < ? THEN 1 ELSE count+1 END, expires=CASE WHEN expires < ? THEN ? ELSE expires END RETURNING count').bind(id,time+3600,time,time,time+3600).first<{count:number}>();if(!record||record.count>max)throw new HttpError(429,'Too many requests. Please try again later.');}
export async function bounded(req:Request,max=600000){if(Number(req.headers.get('content-length'))>max)throw new HttpError(413,'File or request is too large.');const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new HttpError(413,'File or request is too large.');}chunks.push(value);}const output=new Uint8Array(size);let at=0;for(const c of chunks){output.set(c,at);at+=c.length;}return output;}
export async function jsonBody(req:Request){try{return JSON.parse(new TextDecoder().decode(await bounded(req)));}catch(e){if(e instanceof HttpError)throw e;throw new HttpError(400,'Invalid request data.');}}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new HttpError(403,'Please submit from this website.');}
export async function razor(path:string,body?:object){const e=runtime();if(!e.RAZORPAY_KEY_ID||!e.RAZORPAY_KEY_SECRET)throw new HttpError(503,'Payments are not connected yet.');const res=await fetch('https://api.razorpay.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Basic '+btoa(e.RAZORPAY_KEY_ID+':'+e.RAZORPAY_KEY_SECRET),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!res.ok)throw new HttpError(502,'The payment provider could not complete this request. Check your order before trying again.');return res.json() as Promise<any>;}
export function reply(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
